image: maven:latest

stages:
- test
- check
- install

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
  - .m2/repository/
  - target/

check:
  stage: check
  script:
  - mvn qulice:check -Pqulice

install:
  stage: install
  script:
  - mvn clean install -Pqulice

test:
  stage: test
  script:
  - mvn test