image: maven:latest

stages:
- install
- deploy

cache:
  paths:
  - .m2/repository/
  - target/

install_job:
  stage: install
  only:
  - branches
  script:
  - mvn -e clean install -Pqulice

deploy_job:
  stage: deploy
  only:
  - tags
  script:
  - mvn clean deploy -Dmaven.test.skip=true